export interface Country {

  name?: {common?: string, official?:string, nativeName?:{}},
  tld?: string[],
  cca2?: string,
  ccn3?: string,
  cca3?: string,
  cioc?: string,
  independent?: boolean,
  status?: string,
  unMember?: boolean,
  currencies?: {},
  idd?: {},
  capital?: string[],
  altSpellings?: string[],
  region?: string,
  subregion?: string,
  languages?: {},
  translations?: {},
  latlng?: number[],
  landlocked?: boolean,
  borders?: string[],
  area?: number,
  demonyms?: {},
  flags?: {png:string, svg:string},
  maps?: {},
  population?: number,
  gini?: {},
  fifa?: string,
  car?: {},
  flag?:string,
  timezones?: string[],
  continents?: string[],
  coatOfArms?: {},
  startOfWeek?: string,
  capitalInfo?: {},
  postalCode?: {}

}
